twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    #ajout du theme bootstrap4 aux forms#
    form_themes: ['bootstrap_4_layout.html.twig']
